// <auto-generated/>
//-----------------------------------------------------------------------
// <copyright file="ExceptionsMiddleware.cs" company="Gabriel Castillo">
//     Company copyright tag.
// </copyright>
//-----------------------------------------------------------------------
namespace Adopters.Business.Caching
{
    /// <summary>
    /// The Cache Keys
    /// </summary>
    public static class CacheKeys
    {
        /// <summary>
        /// The notifications all
        /// </summary>
        public const string NOTIFICATIONS_ALL = "cache.notifications.all";
    }
}